ASP.NET MVC/UsedClothes/UsedClothes/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UsedClothes.Models;
using System.Web.Security;

namespace UsedClothes.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        UCEntities storeDB = null;
        // private  Guid userId;   
            public CheckoutController()       : this(new UCEntities())
            {
        
            }

            public CheckoutController(UCEntities entities  )
            {
                storeDB = entities;                
            }
        //
        // GET: /Checkout/
       
        

        //
        // GET: /Checkout/AddressAndPayment
        public ActionResult AddressAndPayment()
        {
            return View();
        }

        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);

            try
            {
                order.BuyerId = (Guid)Membership.GetUser(User.Identity.Name).ProviderUserKey;
                    order.OrderDate = DateTime.Now;

                    //Save Order
                    storeDB.AddToOrders(order);
                    storeDB.SaveChanges();
                    //Process the order
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    
                    var items=cart.GetCartItems();
                    foreach (var i in items)
                    {
                        int? AvailableItems = storeDB.Clothes.Where(x => x.ClothesId == i.ClothesId).FirstOrDefault().Quantity;
                        if (i.Quantity >= AvailableItems)
                        {
                            storeDB.Clothes.Where(x => x.ClothesId == i.ClothesId).FirstOrDefault().Quantity = 0;
                            storeDB.Clothes.Where(x => x.ClothesId == i.ClothesId).FirstOrDefault().IsSold = true;
                        }
                        else if (i.Quantity < AvailableItems)
                        {
                            storeDB.Clothes.Where(x => x.ClothesId == i.ClothesId).FirstOrDefault().Quantity -= i.Quantity;

                        }
                    }
                    storeDB.SaveChanges();
                    cart.CreateOrder(order);

                    return RedirectToAction("Complete",
                        new { id = order.OrderId });
                
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }
        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            Guid userId=(Guid)Membership.GetUser(User.Identity.Name).ProviderUserKey;
            // Validate customer owns this order
            bool isValid = storeDB.Orders.Any(
                o => o.OrderId == id &&
                o.BuyerId ==userId) ;

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

ASP.NET MVC/UsedClothes/UsedClothes/Views/Checkout/AddressAndPayment.cshtml
@model UsedClothes.Models.Order
@using ClientDependency.Core.Mvc
@{
    ViewBag.Title = "Address And Payment";
    //Html.RequiresJs("jquery-1.8.3.js", "Scripts", 1);
    Html.RequiresJs("jquery-1.8.3.min.js", "Scripts", 1);
    //Html.RequiresCss("Checkout.css", "Content",2);
  //  Html.RequiresJs("jquery.validate.min.js", "Scripts", 2);
  //  Html.RequiresJs("jquery.validate.unobtrusive.min.js", "Scripts", 2);
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@*<h2>AddressAndPAyment</h2>*@

<div class="list-rows">
@using (Html.BeginForm("AddressAndPayment", "Checkout", FormMethod.Post, new { @class = "checkout" }))
{
    @Html.ValidationSummary(true)
   @* <fieldset>*@
        <legend>Shipping Information</legend>
    
       <p class="list-label">
            @Html.LabelFor(model => model.FirstName)
        </p>
        <p class="fieldwrap"> 
            @Html.EditorFor(model => model.FirstName)
        </p>
        <p class="validwrap">
            @Html.ValidationMessageFor(model => model.FirstName)
        </p>

        <p class="list-label">
            @Html.LabelFor(model => model.LastName)
        </p>
        <p class="fieldwrap"> 
            @Html.EditorFor(model => model.LastName)
         </p>
        <p class="validwrap">
            @Html.ValidationMessageFor(model => model.LastName)
        </p>

      <p class="list-label">
            @Html.LabelFor(model => model.Address)
        </p>
        <p class="fieldwrap"> 
            @Html.EditorFor(model => model.Address)
         </p>
        <p class="validwrap">
            @Html.ValidationMessageFor(model => model.Address)
        </p>

       <p class="list-label">
            @Html.LabelFor(model => model.City)
        </p>
        <p class="fieldwrap"> 
            @Html.EditorFor(model => model.City)
         </p>
        <p class="validwrap">
            @Html.ValidationMessageFor(model => model.City)
        </p>

        <p class="list-label">
            @Html.LabelFor(model => model.State)
        </p>
        <p class="fieldwrap"> 
            @Html.EditorFor(model => model.State)
         </p>
        <p class="validwrap">
            @Html.ValidationMessageFor(model => model.State)
        </p>

        <p class="list-label">
            @Html.LabelFor(model => model.PostalCode)
        </p>
        <p class="fieldwrap"> 
            @Html.EditorFor(model => model.PostalCode)
         </p>
        <p class="validwrap">
            @Html.ValidationMessageFor(model => model.PostalCode)
        </p>

       <p class="list-label">
            @Html.LabelFor(model => model.Country)
        </p>
        <p class="fieldwrap"> 
            @Html.EditorFor(model => model.Country)
         </p>
        <p class="validwrap">
            @Html.ValidationMessageFor(model => model.Country)
        </p>

      <p class="list-label">
            @Html.LabelFor(model => model.Phone)
        </p>
        <p class="fieldwrap"> 
            @Html.EditorFor(model => model.Phone)
         </p>
        <p class="validwrap">
            @Html.ValidationMessageFor(model => model.Phone)
        </p>

       <p class="list-label">
            @Html.LabelFor(model => model.Email)
        </p>
        <p class="fieldwrap"> 
            @Html.EditorFor(model => model.Email)
         </p>
        <p class="validwrap">
            @Html.ValidationMessageFor(model => model.Email)
        </p>
        <br />
        <div style=" margin-right:262px; float:right;">        
            <p class="button">
                <input type="submit" value="Submit order" />                  
            </p>
        </div>

        @*<p>
            <input type="submit" value="Submit order" />
        </p>*@
  @*  </fieldset>*@
}

</div>

ASP.NET MVC/UsedClothes/UsedClothes/Views/Checkout/Complete.cshtml
@model int
@{
    ViewBag.Title = "Checkout Complete";
}
<h2>Checkout Complete</h2>
<p>Thanks for your order! Your order number is: @Model</p>
<p>How about shopping for some more clothes in our 
    @Html.ActionLink("dresm",
"Index", "Home")
</p>