ASP.NET MVC/UsedClothes/UsedClothes/Controllers/ClothesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing.Imaging;
using System.Drawing;
using System.IO;
using UsedClothes.Models;
using System.Web.Security;
using UsedClothes.ViewModels;

namespace UsedClothes.Controllers
{
    public class ClothesController :Controller
    {

        UCEntities uCEntities = null;
 
        //poprawic w DB podkategorie dla dzieci

         public ClothesController()       : this(new UCEntities())
        {
        }

         public ClothesController(UCEntities entities)
        {
            uCEntities = entities;
        }

         private string StorageRoot
         {
             get { return Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Files/")); } //Path should! always end with '/'
         }

        private Guid getUserId()
        {
         MembershipUser user = Membership.GetUser(HttpContext.User.Identity.Name);
          return  (Guid)user.ProviderUserKey;
        }
        //Category gender
         private IList<Gender> GetGenders()
         {
             List<Gender> g = new List<Gender>();
             g.Add(new Gender(0,"Damska"));
             g.Add(new Gender(1,"Męska"));
             g.Add(new Gender(2,"Dziecięca"));

             return g;
         }

         private IList<UsedClothes.Models.Type> GetTypes(int genderId)
         {
             if (genderId == 2)
             {
                 return uCEntities.Types.Where(t => t.Sex==null ).ToList();
             }

             bool? gender=true;

             if (genderId == 0)
                 gender = false;
             else if (genderId == 1)
                 gender = true;
             return uCEntities.Types.Where(t => t.Sex == gender).ToList();

             
         }

         private IList<UsedClothes.Models.SubType> GetSubTypes(/*int genderId,*/int typeId)
         {
             return uCEntities.GetSubTypesInType(typeId).ToList();
             //return null;
         }

         [AcceptVerbs(HttpVerbs.Get)]
         public JsonResult LoadTypesByGender(string id)
         {
             if ( String.IsNullOrEmpty(id))
                 return null;

            // System.Threading.Thread.Sleep(1500);
             var modelList = this.GetTypes(Convert.ToInt32(id));

             var modelData = modelList.Select(m => new SelectListItem()
             {
                 Text = m.TypeName,
                 Value = m.TypeId.ToString(), 

             });

             return Json(modelData, JsonRequestBehavior.AllowGet);
         }

        //
         [AcceptVerbs(HttpVerbs.Get)]
         public JsonResult LoadSubTypesByType(string id)
         {
             if (String.IsNullOrEmpty(id))
                 return null;

             var modelList = this.GetSubTypes(Convert.ToInt32(id));

             var modelData = modelList.Select(m => new SelectListItem()
             {
                 Text = m.SubTypeName,
                 Value = m.SubTypeId.ToString(),

             });

             return Json(modelData, JsonRequestBehavior.AllowGet);
         }

         private IList<UsedClothes.Models.Size> GetSizes(int id)
        {

            return uCEntities.GetSizesForType(id).ToList();
        }

         [AcceptVerbs(HttpVerbs.Get)]
         public JsonResult LoadSizesByType(string id)
         {
             if (String.IsNullOrEmpty(id))
                 return null;

             var modelList = this.GetSizes(Convert.ToInt32(id));

             var modelData = modelList.Select(m => new SelectListItem()
             {
                 Text = m.SizeName,
                 Value = m.SizeId.ToString(),

             });

             return Json(modelData, JsonRequestBehavior.AllowGet);
         }

         public ActionResult Autocomplete(string term)
         {            
             var items = uCEntities.Brands.Select(x => x.BrandName).ToArray();  //ToList().; 

             var filteredItems = items.Where(
                 item => item.IndexOf(term, StringComparison.InvariantCultureIgnoreCase) >= 0
                 );
             return Json(filteredItems, JsonRequestBehavior.AllowGet);
         }

        //
        // GET: /Clothes/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Genders = GetGenders();
           // ViewBag.Types = GetTypes(0);
            ViewBag.Types=uCEntities.Types.ToList();
            //ViewBag.SubTypes=GetSubTypes(1);
            ViewBag.SubTypes = uCEntities.SubTypes.Distinct().ToList();
            ViewBag.Sizes = uCEntities.Sizes.ToList();
            ViewBag.Materials = uCEntities.Materials.ToList();
            ViewBag.Colors = uCEntities.Colors.ToList();
            ViewBag.Patterns = uCEntities.Patterns.ToList();
            return View();
        }


        private byte[] databaseFilePut(string varFilePath)
        {
            var path = StorageRoot + Path.GetFileName(varFilePath);
            byte[] file;
            using (var stream = new FileStream(path, FileMode.Open, FileAccess.Read))
            {
                using (var reader = new BinaryReader(stream))
                {
                    return file = reader.ReadBytes((int)stream.Length);

                }
            }
        }

        private void deleteFile(string varFilePath)
        {
            var path = StorageRoot + Path.GetFileName(varFilePath);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
        }

        //
        // POST: /Clothes/Create
        


        [HttpPost, Authorize]
        public ActionResult AddClothes(ClothModelView cm)
        {
            try
            {              
               // Guid d=System.Guid.Parse(b8dc0c86-4e18-4807-a94e-44c0b51069ac);
                System.Data.Objects.ObjectParameter newClothesId = new System.Data.Objects.ObjectParameter("NewClothesId", 0);
                uCEntities.InsertNewClothes(cm.Name, cm.Description,getUserId(), cm.Price, cm.Sex, cm.Condition, cm.BrandName, cm.ColorId, cm.SizeId, cm.Quantity, cm.TypeId, System.DateTime.Now, cm.MaterialId, cm.PatternId, cm.IsVintage, cm.SubTypeId, newClothesId);

                if (cm.PhotoNameF != null)
                    { uCEntities.InsertPicture("F", databaseFilePut(cm.PhotoNameF), (int)newClothesId.Value); deleteFile(cm.PhotoNameF); }
                if (cm.PhotoNameB != null)
                    { uCEntities.InsertPicture("B", databaseFilePut(cm.PhotoNameB), (int)newClothesId.Value); deleteFile(cm.PhotoNameB); }
                if (cm.PhotoNameD0 != null)
                    { uCEntities.InsertPicture("D0", databaseFilePut(cm.PhotoNameD0), (int)newClothesId.Value); deleteFile(cm.PhotoNameD0); }
                if (cm.PhotoNameD1 != null)
                    { uCEntities.InsertPicture("D1", databaseFilePut(cm.PhotoNameD1), (int)newClothesId.Value); deleteFile(cm.PhotoNameD1); }


                uCEntities.SaveChanges();

               

                TempData["Message"] = string.Format("Ubranie zostało dodane");
                return RedirectToAction("Index", "Home");// ("Detail");



            }
            catch (Exception e)
            {
                //return View();
                return null;
                //return View("AddClothes2");
            }
        }

        [HttpPost, Authorize]
        public ActionResult AddClothes2(ClothModelView cm/*, HttpPostedFileBase Picture*/)
        {
            return null;
        }


       

        //
        // GET: /Clothes/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }
         

        

        private byte[] ImageToBytes(Image img, ImageFormat format)
        {
            MemoryStream mstream = new MemoryStream();
            img.Save(mstream, format);
            mstream.Flush();
            return mstream.ToArray();
        }

        //
        // GET: /Clothes/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Clothes/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Clothes/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Clothes/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Index(string gender, string type =null)
        {
            var Items = uCEntities.LastWomensPositions;
            List<ShortClothesViewModel> model=new List<ShortClothesViewModel>();
            foreach (var item in Items)
            {
                model.Add(new ShortClothesViewModel { 
                     ClothesId=item.ClothesId,
                      ClothesName=item.ClothesName,
                       Image=item.Image,
                        PictureId=item.PictureId,
                         Price=item.Price.Value,
                          SellerId=item.SellerId.Value,
                           SizeName=item.SizeName
                });
            }

            return View();
        }


    }
}

ASP.NET MVC/UsedClothes/UsedClothes/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Web.Mvc;
using UsedClothes.Models;
using UsedClothes.ViewModels;
using System.Collections.Generic;
using System;

namespace UsedClothes.Controllers
{
    public class ShoppingCartController : Controller
    {
        UCEntities storeDB = new UCEntities();

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult UpdateTotal(string quantity, string clothesid)
        {
            if (String.IsNullOrEmpty(quantity) || String.IsNullOrEmpty(clothesid))
                return null;

            int clothesId=System.Int32.Parse(clothesid);
            int quanty=System.Int32.Parse(quantity);
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var cartId = cart.GetCartId(this.HttpContext);

            
            storeDB.ShoppingCarts.Where(x => x.ClothesId == clothesId && x.CartId == cartId).FirstOrDefault().Quantity = quanty;

            //position.Quantity = quanty;
            storeDB.SaveChanges();
           //var  cart1 = ShoppingCart.GetCart(this.HttpContext);
          //var data = cart1.GetTotal();
            var data = cart.GetTotal();
            
            return Json(data, JsonRequestBehavior.AllowGet);
        }      
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            List<int> dg=new List<int>(){0,1,2,3,4};
            var modelData = dg.Select(m => new SelectListItem()
            {
                Text = m.ToString(),
                Value = m.ToString(),

            });


            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            
            

            return View(viewModel);
        }

        private bool CanAdd(int clothesId,string cartId)
        {
            var clothesInCart=storeDB.ShoppingCarts.Where(x => x.ClothesId == clothesId && x.CartId == cartId).FirstOrDefault();
            var clothesQuantity = storeDB.Clothes.Single(cloth => cloth.ClothesId == clothesId).Quantity;

            if ((clothesInCart == null) && (clothesQuantity > 0))
                return true;
            //if (clothesInCart != null){
            //    if(clothesInCart.Quantity >= clothesQuantity)
            //    return false;
            //}
            if (clothesInCart != null)
            {
                if (clothesInCart.Quantity < clothesQuantity)
                    return true;
            }
            return false;
        }

        //
        // GET: /Store/AddToCart/5
       [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult AddToCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);            
            string cartId = cart.GetCartId(this.HttpContext);
            // Retrieve the cloth from the database
            var addedCloth = storeDB.Clothes
                .Single(cloth => cloth.ClothesId == id);
            int data;
            //if (addedCloth.Quantity == 0)
           if (!CanAdd(id,cartId))
            {
                data = -1;
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            // Add it to the shopping cart
            //var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedCloth);            
            data=cart.GetCount();
            //RedirectToAction("Index");
           
           return Json(data, JsonRequestBehavior.AllowGet);
           // return Json(data);
        }
         //var ControllerContext.RouteData.GetRequiredString("action")
       [AcceptVerbs(HttpVerbs.Get)]
       public JsonResult AddToCart0(int id)
       {
           var cart = ShoppingCart.GetCart(this.HttpContext);
           string cartId = cart.GetCartId(this.HttpContext);
           // Retrieve the cloth from the database
           var addedCloth = storeDB.Clothes
               .Single(cloth => cloth.ClothesId == id);

           int data;
           if (!CanAdd(id, cartId))
           {
               data = -1;
               return Json(data, JsonRequestBehavior.AllowGet);
           }
           // Add it to the shopping cart
          

           //var cart = ShoppingCart.GetCart(this.HttpContext);

           cart.AddToCart(addedCloth);
           //data = cart.GetCount();
           data = 1;

           return Json(data, JsonRequestBehavior.AllowGet);
           //return RedirectToAction("Index");
       }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the positionName to display confirmation
            string positionName = storeDB.ShoppingCarts
                .Single(item => item.RecordId == id).Cloth.ClothesName;

            // Remove from cart
           // int itemCount = cart.RemoveFromCart(id);
            cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(positionName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                //ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

ASP.NET MVC/UsedClothes/UsedClothes/Views/Shared/_Layout.cshtml
@using ClientDependency.Core
@using ClientDependency.Core.Mvc
<!DOCTYPE html>
<html>
<head>
	<title>@ViewBag.Title</title>
	
	@MvcHtmlString.Create(Html.RenderCssHere(new List<IClientDependencyPath>
												{
													new BasicPath("Base", "~/Content/themes/base"),
													new BasicPath("Content", "~/Content")
												}))

	@MvcHtmlString.Create(Html.RenderJsHere(new List<IClientDependencyPath>
											   {
												   new BasicPath("Scripts", "~/Scripts"),
												   new BasicPath("googleCDN", "http://ajax.googleapis.com/ajax/libs/"),
												   new BasicPath("Content", "~/Content")
												   
											   }))

	@{
        Html.RequiresCss("Site.css", "Content", 1);
	}

   @* <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.8.3.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.9.2.min.js")" type="text/javascript"></script>
      <script src="@Url.Content("~/Scripts/autocomplete.js")" type="text/javascript"></script>

   *@

</head>
<body>
   <div class="page">
       <div id="header">
         <div id="logo" style="clear:none;" >
            <a href="@(Url.Action("Index","Home"))" >
            <img id="imglogo" src="@Url.Content("~/Content/logo.png")" />
            </a>
         </div>
        
         @if (Request.IsAuthenticated)
        {
        <div id="changePassword" style="clear:none;">
           <a href="@Url.Action("ChangePassword", "Account")">Zmien haslo </a>
        </div>
        }
               
        <div id="logindisplay" style="clear:none;">
      
            @Html.Partial("_LogOnPartial")
        </div> 

        <div id="topmenu" style="clear:none;">
            @Html.Partial("_TopMenu")          
               @{Html.RenderAction("CartSummary", "ShoppingCart");}          
         </div>

        
    @Html.Partial("_Menu")
     </div>
    
  <div id="main">
  
  <h2 id="msg0">@ViewBag.Message</h2>
<h4 id="msg">@TempData["Message"]</h4>
    
     
            @RenderBody()
     </div>   
     <div class="clear">
        </div>
    

    </div>


<div class="footer">Copyright &copy; 2012 uOdzież</div>
</body>
</html>

ASP.NET MVC/UsedClothes/UsedClothes/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

ASP.NET MVC/UsedClothes/UsedClothes/Views/Shared/_Menu.cshtml
<ul id="menu">
                <li>
                    @Html.ActionLink("Womens", "Index", "Clothes", new {gender="Womens" })
                    <span>
                        @Html.ActionLink("Tops", "Index", "Home")
                        @Html.ActionLink("Dresses", "Index", "Home")
                        @Html.ActionLink("Bottoms", "Index", "Home")
                        @Html.ActionLink("Headwear", "Index", "Home")
                        @Html.ActionLink("Accessorie", "Index", "Home")
                        @Html.ActionLink("Outerwear", "Index", "Home")
                        @Html.ActionLink("Shoes", "Index", "Home")
                    </span>
                </li>
                <li>
                    @Html.ActionLink("Mens", "Index", "Clothes", new { gender = "Mens" })
                    <span>
                        @Html.ActionLink("Tops", "Index", "Home")                        
                        @Html.ActionLink("Bottoms", "Index", "Home")
                        @Html.ActionLink("Headwear", "Index", "Home")
                        @Html.ActionLink("Accessorie", "Index", "Home")
                        @Html.ActionLink("Outerwear", "Index", "Home")
                        @Html.ActionLink("Shoes", "Index", "Home")
                    </span>
                </li>
                <li>
                    @Html.ActionLink("Youth", "Index", "Clothes", new { gender = "Youths" })
                    <span>
                        @Html.ActionLink("Boys", "Index", "Home")
                        @Html.ActionLink("Girls", "Index", "Home")
                        @Html.ActionLink("Toodler", "Index", "Home")                        
                        @Html.ActionLink("Accessorie", "Index", "Home")
                        @Html.ActionLink("Infant", "Index", "Home")                        
                    </span>
                </li>

                               
            
            </ul>







            @*    @if ( Request.IsAuthenticated && HttpContext.Current.User.IsInRole( "Admin" ) ) *@

            @*((Roles.IsUserInRole(User.Identity.Name, @"SuperAdmin"))&&(CanAddOffer(offer.AuctionId, offer.UserId)))*@

ASP.NET MVC/UsedClothes/UsedClothes/Views/Shared/_TopMenu.cshtml
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Add Clothes", "Create", "Clothes")
                }
                @Html.ActionLink("Home", "Index", "Home")
                @Html.ActionLink("Info", "Info", "Home")
             