ASP.NET MVC/Inbid/Inbid/Models/Offer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Web.Security;
using Inbid.Validation;

namespace Inbid.Models
{
    [MetadataType(typeof(OfferMetadata))]
    public partial class Offer
    {
        class OfferMetadata
        {
            [HiddenInput(DisplayValue = false)]
            public int OfferId { get; set; }

            [Required(ErrorMessageResourceType = typeof(Resources.Resources), ErrorMessageResourceName = "UserNameRequired")]
            [Range(0, 999999999999)]
            public Decimal StartPrice { get; set; }

            [CurrentPrice("AuctionId","StartPrice")]
            [Range(0, 999999999999)]
            public Decimal CurrentPrice { get; set; }

            public int BDCounter { get; set; }

            [HiddenInput(DisplayValue = false)]
            public int AuctionId { get; set; }

            public Guid UserId { get; set; }

            

            //pole dla dropdownlist ma przejść na UserId
            //public string UserName { get; set; }
        }


        public bool IsHostedBy()
        {
            MembershipUser mu = Membership.GetUser();
            if (mu != null)
            {
                Guid currentUserId = (Guid)mu.ProviderUserKey;
                return (UserId == currentUserId) ? true : false;
            }
            return false;
        }

        public decimal Change ()
        {
            return StartPrice != 0 ? Math.Round(100 * Math.Abs((StartPrice-CurrentPrice)) / StartPrice, 2) : 0;
        }

        public bool IsOnline()
        {
            return Membership.GetUser(UserId).IsOnline ? true : false;       
        }

        public string GetUserName()
        {
            
            MembershipUser mu = Membership.GetUser(UserId);
            if (mu != null)
            {
                return mu.UserName;
            }
            return "Problem z dostępem do danych użytkownika";
        }

        

    }
}

ASP.NET MVC/Inbid/Inbid/ViewModels/OfferViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Inbid.Models;

namespace Inbid.ViewModels
{
     
    public class OfferViewModel
    {
        public IEnumerable<Offer> Offers { get; set; }
        public Auction Auction { get; set; }
       // public Users Subscribers { get; set; }
        public IEnumerable<Subscriber> Subscribers { get; set; }
        public Message M { get; set; }
        public IEnumerable<Message> Messages { get; set; }
      
    }
}

   

ASP.NET MVC/Inbid/Inbid/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inbid.Models;
using Inbid.ViewModels;
using Inbid;
using Newtonsoft.Json;
using Inbid.Infrastructure;

using System.Data;
using System.Web.Security;
using Inbid.Helpers;
using System.Threading;
using System.Globalization;
using Resources;
using System.Collections;
using System.Text;


namespace Inbid.Controllers
{
    [HandleErrorWithELMAH]
    [Authorize]
    public class OfferController : BaseController
    {

        string[] stats = new string[] { "Nie rozpocżeta", "Trwa", "Zawieszona", "Zakończona" };

        TimeSpan deathTimeExtend=TimeSpan.FromSeconds(30);

        InBidEntities InBidEntities = null;


        // GET: /Auction/

        string SetState(string[] stats, int id)
        {
            var auction = InBidEntities.Auctions.Where(x => x.AuctionId == id).First();

            if (auction.StartTime > System.DateTime.Now.ToUniversalTime())
            {
                return stats[0];
            }
            else if (auction.EndTime < System.DateTime.Now.ToUniversalTime())
            {
                return stats[3];
            }
            else if ((auction.EnableDisable == true) && (auction.StartTime < System.DateTime.Now.ToUniversalTime()) && (auction.EndTime > System.DateTime.Now.ToUniversalTime()))
            {
                return stats[1];
            }
            else if ((auction.EnableDisable == false) && (auction.StartTime < System.DateTime.Now.ToUniversalTime()) && (auction.EndTime > System.DateTime.Now.ToUniversalTime()))
            {
                return stats[2];
            }
            return null;
        }

        public OfferController()
            : this(new InBidEntities())
        {
        }

        public OfferController(InBidEntities entities)
        {
            InBidEntities = entities;
        }


        bool CanBiding(int id)
        {
            var auction = InBidEntities.Auctions.Where(x => x.AuctionId == id).FirstOrDefault();

            if ((auction.EnableDisable) && (auction.StartTime.ToUniversalTime() < System.DateTime.Now.ToUniversalTime()) && (auction.EndTime.ToUniversalTime() > System.DateTime.Now.ToUniversalTime()))
            {
                return true;
            }

            return false;
        }

       


        [HttpPost]
        public ActionResult EnableDisableAuction(int id)
        {
            Auction auction = InBidEntities.Auctions.Where(x => x.AuctionId == id).First();

            if (auction.EnableDisable)
            {
                auction.EnableDisable = false;
                auction.DisableStartTime = DateTime.UtcNow;
            }
            else
            {
                auction.EnableDisable = true;
                TimeSpan suspendTime = DateTime.UtcNow - auction.DisableStartTime.Value;
                //auction.EndTime += System.TimeSpan.FromHours(System.Double.Parse(Request.Cookies["TimeZone"].Value));
                auction.EndTime+=suspendTime;
                
            }
            //auction.EnableDisable = (auction.EnableDisable) ? false : true;
            InBidEntities.SaveChanges();
            return null;
        }


        decimal getCurrentPrice(int auctionNumber)
        {
            IQueryable<Offer> offers = GetOffers(auctionNumber);
            if (offers == null)
                return 0;
            else if (offers.Count() > 0)
            {
                return offers.Skip(0).First().CurrentPrice;
            }
            return 0;
        }

        decimal SetCurrentPriceWithJump(int auctionNumber)
        {
            var auction = InBidEntities.Auctions.Where(x => x.AuctionId == auctionNumber).FirstOrDefault();
            int offersCount = InBidEntities.Offers.Where(x => x.AuctionId == auctionNumber).Count();
            decimal currentPrice = auction.CurrentPrice;
            //decimal startPrice = auction.StartPrice;
            decimal minJump = auction.MinJump;
            bool direction = auction.Direction;
            //decimal newCurrentPrice = 0;
            if (direction)
            {
                if (offersCount == 0)
                    return currentPrice;
                if (currentPrice - minJump > 0)
                {
                    return currentPrice - minJump;
                }
                else
                    return 0;
            }
            else
            {
                if (offersCount == 0)
                    return currentPrice;
                else
                    return currentPrice + minJump;
            }
        }

        // [Authorize]       
        public ActionResult Create(int auctionNumber)
        {
            if (!CanBiding(auctionNumber)) //aukcja nie trwa
                return View("CantBiding");

            Offer offer = null;
            if (Roles.IsUserInRole(User.Identity.Name, @"SuperAdmin"))
            {
                int freeUsers = PopulateUserWithoutAuctionDropDownList(auctionNumber);

                if (freeUsers == 0)
                    return View("OverLimitTotal");



                offer = new Offer()
                {
                    AuctionId = auctionNumber,
                    StartPrice = SetCurrentPriceWithJump(auctionNumber)

                };

                return View(offer);
            }
            if (!CanAddOffer(auctionNumber))
                return View("OverLimit");

            if (Roles.IsUserInRole(User.Identity.Name, @"Bidder"))
            {
                offer = new Offer()
                {
                    AuctionId = auctionNumber,
                    StartPrice = SetCurrentPriceWithJump(auctionNumber)
                };

                return View(offer);
            }
            return View("AccessDenied");
        }

        //
        // POST: Offer/Create

        [HttpPost]
        public ActionResult Create(Offer offer)
        {
            if (!CanBiding(offer.AuctionId))
                return View("CantBiding");

            if (!CanAddOffer(offer.AuctionId, offer.UserId))
                return View("OverLimit");
            if ((!Roles.IsUserInRole(User.Identity.Name, @"SuperAdmin")) && (!Roles.IsUserInRole(User.Identity.Name, @"Bidder")))
                return View("AccessDenied");

            if (ModelState.IsValid)
            {

                offer.CurrentPrice = offer.StartPrice;
                offer.BDCounter = 0;
                offer.JoinedDate = System.DateTime.UtcNow;
                SetAuctionCurrentPrice(offer.AuctionId, 0, offer.CurrentPrice, false);


                if ((Roles.IsUserInRole(User.Identity.Name, @"SuperAdmin")) && (CanAddOffer(offer.AuctionId, offer.UserId)))
                {

                }
                else
                {
                    MembershipUser mu = Membership.GetUser();
                    Guid currentUserId = (Guid)mu.ProviderUserKey;
                    offer.UserId = currentUserId;
                }
                offer.BDCounter = 0;

                var offerAuction = InBidEntities.Auctions.Where(x => x.AuctionId == offer.AuctionId).FirstOrDefault();
                var timeToEndAuction = offerAuction.EndTime - DateTime.UtcNow;
                if (timeToEndAuction <= deathTimeExtend)
                    offerAuction.EndTime += timeToEndAuction;

                InBidEntities.AddToOffers(offer);
                InBidEntities.SaveChanges();

                return RedirectToAction("Index", new { auctionNumber = offer.AuctionId });
            }
            PopulateUserWithoutAuctionDropDownList(offer.AuctionId, offer.UserId);
            return View(offer);
        }

        void changeDateIn1Auction(Auction a)
        {
            a.StartTime += System.TimeSpan.FromHours(System.Double.Parse(Request.Cookies["TimeZone"].Value));
            a.EndTime += System.TimeSpan.FromHours(System.Double.Parse(Request.Cookies["TimeZone"].Value));
        }
        [HttpGet]
        public ActionResult Index(int auctionNumber)
        {
            //System.DateTime.Now.T
            var offers = GetOffers(auctionNumber);
            var auction = InBidEntities.Auctions.Where(x => x.AuctionId == auctionNumber).SingleOrDefault();

            //var messages = Messages.Informations;
            var m = new Message();
            m.AuctionId = auctionNumber;

            var usersInAuction = (from o in InBidEntities.Offers
                                  join a in InBidEntities.aspnet_Users on o.UserId equals a.UserId
                                  where o.AuctionId == auctionNumber
                                  select new
                                  {
                                      a.UserId,
                                      a.UserName
                                  });

            Guid currentUserId = new Guid();


            MembershipUser mu = Membership.GetUser();
            if (mu != null)
            {
                currentUserId = (Guid)mu.ProviderUserKey;
            }

            List<Message> msg = new List<Message>();

            var messages = ((List<Message>)HttpContext.Application["Messages"]).Where(x => x.AuctionId == auctionNumber);

            foreach (var s in messages)
            {
                foreach (var g in s.Subscribers)
                {
                    if (g == currentUserId)
                    {
                        msg.Add(s);
                        break;
                    }
                }

            }





            int counter = offers.Count();
            auction.OfferCounter = counter;
            changeDateIn1Auction(auction);

            HttpContext.Session["offerList"] = offers.ToList();

            OfferViewModel ovm = new OfferViewModel()
            {
                Offers = offers,
                Auction = auction,
                M = m,

                Subscribers = usersInAuction.Select(x => new Subscriber
                {

ASP.NET MVC/Inbid/Inbid/Views/Offer/CantBiding.cshtml
@{
    ViewBag.Title = "Nie można licytować";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Teraz nie można licytować ponieważ aukcja jest zawieszona, nie zaczeła się jeszcze lub się już skończyła</h2>

ASP.NET MVC/Inbid/Inbid/Views/Offer/Create.cshtml
@model Inbid.Models.Offer

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
@*<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>*@

@using (Html.BeginForm() ) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Offer</legend>
        <div class="editor-label">
            @Html.HiddenFor(model => model.OfferId)
        </div>

        <div class="editor-label">
            @Html.HiddenFor(model => model.AuctionId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartPrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartPrice)
            @Html.ValidationMessageFor(model => model.StartPrice)
               @Html.ValidationMessageFor(model => model.CurrentPrice)
        </div>
        
        <div class="editor-label">
            @Html.HiddenFor(model => model.CurrentPrice)
         
        </div>
        @*<div class="editor-field">
            @Html.EditorFor(model => model.StartPrice)
            @Html.ValidationMessageFor(model => model.StartPrice)
        </div>*@

        @if ((Request.IsAuthenticated) && (Roles.IsUserInRole(User.Identity.Name, @"SuperAdmin")))
        {
        <div class="editor-label">
          Użytkownik
        </div>
        <div class="editor-field">
         @Html.DropDownList("UserId", "")
         @Html.ValidationMessageFor(model => model.UserId)
        </div>
        }
        @*<div class="editor-label">
            @Html.LabelFor(model => model.CurrentPrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurrentPrice)
            @Html.ValidationMessageFor(model => model.CurrentPrice)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BDCounter)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BDCounter)
            @Html.ValidationMessageFor(model => model.BDCounter)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AuctionId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AuctionId)
            @Html.ValidationMessageFor(model => model.AuctionId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>*@

        <p>
            <input type="submit" value="Create" />
            
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Wróć do aukcji", "Index", new {auctionNumber=Request.QueryString["auctionNumber"] } )
</div>

ASP.NET MVC/Inbid/Inbid/Views/Offer/Delete.cshtml
@model Inbid.Models.Offer

@using Resources

@{
	ViewBag.Title = Resources.DeleteConfirmation + ": " + Model.OfferId;
}

<h2>
	@Resources.DeleteConfirmation
</h2>

<div>
	<p>Potwierdz usuniecie oferty 
    @*@Resources.PleaseConfirmCancelOffer*@
	<i> @Model.OfferId ? </i> </p>
</div>
	


@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> 
     
    </p>
}
   @Html.ActionLink("Back to List", "Index", new {auctionNumber=Model.AuctionId })

ASP.NET MVC/Inbid/Inbid/Views/Offer/Edit.cshtml
@model Inbid.Models.Offer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(function () {
        $(".datefield").datepicker();
    });
 </script>

<h2>Edit</h2>

@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>*@
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@*<script src="@Url.Content("~/Scripts/clientvalidation.js")" type="text/javascript"></script>
*@
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Offer</legend>

        <div class="editor-label">
            @Html.HiddenFor(model => model.OfferId)
        </div>
       
   <div class="editor-label">
            @Html.HiddenFor(model => model.AuctionId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CurrentPrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurrentPrice)
            @Html.ValidationMessageFor(model => model.CurrentPrice)
        </div>

     

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to Auction", "Index", new { auctionNumber=Model.AuctionId })
    @Html.ActionLink("Delete", "Delete", new {id=Model.OfferId })
</div>

ASP.NET MVC/Inbid/Inbid/Views/Offer/InvalidOwner.cshtml
@using Resources

@{
	ViewBag.Title = Resources.YouDoNotOwnThisAuction;
}

<h2>@Resources.ErrorAccessingAuction</h2>

ASP.NET MVC/Inbid/Inbid/Views/Offer/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nie znaleziono oferty</h2>

ASP.NET MVC/Inbid/Inbid/Views/Offer/OverLimit.cshtml
@{
    ViewBag.Title = "OverLimit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Twoja firma ma już oferte  dla tej aukcji</h2>

ASP.NET MVC/Inbid/Inbid/Views/Offer/OverLimitTotal.cshtml
@{
    ViewBag.Title = "OverLimitTotal";
}

<h2>Wszyscy zarejestrowani biderzy uczestniczą w tej aukcji</h2>

ASP.NET MVC/Inbid/Inbid/Views/Offer/_AuctionDetails.cshtml
@model Inbid.ViewModels.OfferViewModel
@using Resources


         
<div id="auctionProporties">
    <table id="tbAuctionProporties">
     <thead>
            <tr>
            <td colspan="6" class="hea">
            Informacje o Aukcji
            </td>

            </tr>
           <tr />
        </thead>
        <tr>
            <td class="label">
                ID:
            </td>
            <td class="secondColumn">
                @Model.Auction.AuctionNumber
            </td>
            <td class="label">
           Currency:
            </td >
            <td>
                @Model.Auction.Currency        
            </td>
            <td class="label">
              Min Jump:
            </td>
              <td>
              @Model.Auction.MinJump.ToString("N02")
            </td>
        </tr>
        <tr>
        <td class="label">
             Publisher:
            </td>            
            <td>
             @Model.Auction.GetUserName()
            </td>
                <td class="label">
               Kupno/Sprzedaz
            </td>
             <td>
             @if (Model.Auction.Direction == true)
             {
            @Resources.Reverse
             }
             else if (false == Model.Auction.Direction)
             {
            @Resources.Forward
             }
            </td>     
           
            <td class="label">
              Start Time:
            </td>
              <td>
              @Model.Auction.StartTime
            </td>
        </tr>
        <tr>
            <td rowspan="2" class="label">
             Name:
            </td>
             <td rowspan="2">
             @Html.DisplayTextFor(model => model.Auction.Name)
         @*     @Model.Auction.Name*@
            </td>
            <td class="label">
           Start Price:
            </td>
            <td>
              @Model.Auction.StartPrice.ToString("N02")
            </td>
              <td class="label">
              End Time:
            </td>
             <td id="endTime">
              @Model.Auction.EndTime
            </td>
        </tr>
        <tr>
                 
            
            <td class="label">
            Current Price:
            </td>
            <td>
            @Model.Auction.CurrentPrice.ToString("N02")
            </td>
            <td class="label">
                Status:
            </td>
              <td class="AuctionStatus" state="@Model.Auction.EnableDisable">              
                 @if (@Model.Auction.StartTime.ToUniversalTime() > System.DateTime.Now.ToUniversalTime())
                 {
                    @:Nie rozpoczęta
                 }
                 else if (@Model.Auction.EndTime.ToUniversalTime() < System.DateTime.Now.ToUniversalTime())
                 {
                    @:Zakończona   
                 }
                 else if ((@Model.Auction.EnableDisable == true) && (@Model.Auction.StartTime.ToUniversalTime() < System.DateTime.Now.ToUniversalTime()) && (@Model.Auction.EndTime.ToUniversalTime() > System.DateTime.Now.ToUniversalTime()))
                 {
                    @:Trwa
                 }
                 else if ((@Model.Auction.EnableDisable == false) && (@Model.Auction.StartTime.ToUniversalTime() < System.DateTime.Now.ToUniversalTime()) && (@Model.Auction.EndTime > System.DateTime.Now.ToUniversalTime()))
                 {
                    @:Zawieszona             
                }
            </td>
        </tr>
        <tr>
            <td  rowspan="2" class="label" >
              Description:
            </td>
            <td rowspan="2" colspan="3" class="description">
                @Model.Auction.Description
            </td>
            
           
            <td class="label">
           Bid counter:
            </td>
              <td>
              @Model.Auction.OfferCounter
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            
           
        </tr>
    </table>

</div>

ASP.NET MVC/Inbid/Inbid/Views/Offer/_DeadlineTimer.cshtml
@model Inbid.ViewModels.OfferViewModel


@*<script src="@Url.Content("~/Scripts/date.format.js")" type="text/javascript"></script>*@


<script type="text/javascript">
    $(document).ready(function () {              

    downCounting();
    //setInterval("downCounting()", 1000);
     
        });

       function downCounting() {
        var year=@Model.Auction.EndTime.Year;
        var month=@Model.Auction.EndTime.Month-1;
        var day=@Model.Auction.EndTime.Day;
        var hour=@Model.Auction.EndTime.Hour;
        var minute=@Model.Auction.EndTime.Minute;
        var second=@Model.Auction.EndTime.Second;

            var auctionEndTime = new Date(year,month,day);
            var now = new Date();           
            var display = auctionEndTime - now;
            var date = getTimeSpan(display);            
            $("#data").html("Do zakończenia aukcji pozostało: "+date.hour+" godzin "+date.minute+" minut "+date.second +" sekund");            
            setInterval("downCounting()", 1000);
        };

        function getTimeSpan(ticks) {
            var d = new Date(ticks);
            return {   
                hour: Math.floor(ticks / 3600000),              
                minute: d.getMinutes(),
                second: d.getSeconds()
            }
        }


    </script>


<label id="data"> </label>

    

ASP.NET MVC/Inbid/Inbid/Views/Offer/_Messanger.cshtml
@model Inbid.ViewModels.OfferViewModel

<table id="tbMessages">
<thead>
<tr><td>
Wiadomości od Właściciela aukcji
</td></tr>
</thead>
<tbody>
@foreach (var item in Model.Messages)
{
<tr id="@item.MessageId">
<td>
@item.Information
</td>
</tr>


}
</tbody>
</table>

<script type="text/javascript">
//    $(document).ready(function () {
//        var period = 5000;   
//         AddMessages(period);
//        

//    });

//    function AddMessages(t) {

//        i = 0;
//        var Rows = new Array();
//        $("#tbMessages tbody tr").each(function () {
//            Rows[i] = $(this).attr("id").toString();
//            i++;
//        });

//        //var Rows = getMessageIds()
//        var id = $("#tOferts").attr("aId");
//        var json = { 'ids':Rows};

//        if (id != '') {
//            jQuery.ajaxSettings.traditional = true;
//            //$.post("/Inbid/Offer/GetMessages/" + id, json,
//            var url = '@Url.Action("GetMessages","Offer")/' + $("#tOferts").attr("aId");

//          //  $.post("GetMessages/" + id, json,
//            $.post(url, json,
//                    function (data) {
//                        if (data != null) {
//                            var newRows = JSON.parse(data);

//                            for (i = 0; i < newRows.length; i++) {

//                                var rowId = newRows[i].MessageId;
//                                var msg = newRows[i].Information;

//                                var insertHtml = '<tr  id="' + rowId + '">' +
//                                                    '<td>' +
//                                                       msg +
//                                                    '</td>' +
//                                                 '</tr>';

////                                $(insertHtml).fadeTo(0, 0, function(){
////                                    $("#tbMessages tbody").prepend(insertHtml).fadeTo('2000',1);
////                                });
//                                
//                                $("#tbMessages tbody").prepend(insertHtml);
//                            }
//                        }
//                    });
//        }
//        t += 5000;
//        setTimeout(function () { AddMessages(t) }, t);
//    }

//    function getMessageIds() {
//        i = 0;
//        var rows = new Array();
//        $("#tbMessages tbody tr").each(function () {
//            //rows[i] = '{\"MessageId\": ' + $(this).attr("id") + '}';
//            //var z = $(this).attr("id").toString();
//            //rows[i] = z;
//            rows[i] = $(this).attr("id").toString();
//            i++;
//        });
//        return rows;
//    }

</script>

ASP.NET MVC/Inbid/Inbid/Views/Offer/_Publisher.cshtml
@model Inbid.ViewModels.OfferViewModel

@*<script src="@Url.Content("~/Scripts/jquery-1.5.2.min.js")" type="text/javascript"></script>*@
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script> @* wywala dwa posty*@

<script src="@Url.Content("~/Scripts/MicrosoftAjax.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/MicrosoftMvcAjax.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/MicrosoftMvcValidation.js")" type="text/javascript"></script>

<div id="messagePublishing">

</div>

@using (Ajax.BeginForm("SendMessage", new AjaxOptions
{
    HttpMethod = "Post",
    OnFailure = "onFailure",
    OnSuccess = "onSuccess"

}))
{
    
    
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Message</legend>
        <div class="editor-label">
            @Html.HiddenFor(model => model.M.AuctionId)
        </div>
       @* <div class="editor-label">
            @Html.LabelFor(model => model.M.Publisher)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.M.Publisher)
            @Html.ValidationMessageFor(model => model.M.Publisher)
        </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.M.Information)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.M.Information)
            @Html.ValidationMessageFor(model => model.M.Information)
        </div>
   
  
  

  <div class="editor-label">
      @Html.LabelFor(model => model.M.Subscribers)
      </div>  
      @foreach (var x in Model.Subscribers)
      {    
        <input type="checkbox"   
         name="Subscribers"
         value="@x.Id"
         checked="checked"   />          
       <text>@x.UserName  </text>          
        <br/> 

      }
        <p>
            <input type="submit" value="Send" />
        </p>
    </fieldset>
}

<script type="text/javascript">
    function onFailure() {
        $("#messagePublishing").text("Wiadomosc nie zostala wyslana");
    }

    function onSuccess() {
        $("#messagePublishing").text("Wiadomosc zostala wyslana");
    }

</script>


 