ASP.NET MVC/UsedClothes/UsedClothes/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Web.Mvc;
using UsedClothes.Models;
using UsedClothes.ViewModels;
using System.Collections.Generic;
using System;

namespace UsedClothes.Controllers
{
    public class ShoppingCartController : Controller
    {
        UCEntities storeDB = new UCEntities();

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult UpdateTotal(string quantity, string clothesid)
        {
            if (String.IsNullOrEmpty(quantity) || String.IsNullOrEmpty(clothesid))
                return null;

            int clothesId=System.Int32.Parse(clothesid);
            int quanty=System.Int32.Parse(quantity);
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var cartId = cart.GetCartId(this.HttpContext);

            
            storeDB.ShoppingCarts.Where(x => x.ClothesId == clothesId && x.CartId == cartId).FirstOrDefault().Quantity = quanty;

            //position.Quantity = quanty;
            storeDB.SaveChanges();
           //var  cart1 = ShoppingCart.GetCart(this.HttpContext);
          //var data = cart1.GetTotal();
            var data = cart.GetTotal();
            
            return Json(data, JsonRequestBehavior.AllowGet);
        }      
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            List<int> dg=new List<int>(){0,1,2,3,4};
            var modelData = dg.Select(m => new SelectListItem()
            {
                Text = m.ToString(),
                Value = m.ToString(),

            });


            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            
            

            return View(viewModel);
        }

        private bool CanAdd(int clothesId,string cartId)
        {
            var clothesInCart=storeDB.ShoppingCarts.Where(x => x.ClothesId == clothesId && x.CartId == cartId).FirstOrDefault();
            var clothesQuantity = storeDB.Clothes.Single(cloth => cloth.ClothesId == clothesId).Quantity;

            if ((clothesInCart == null) && (clothesQuantity > 0))
                return true;
            //if (clothesInCart != null){
            //    if(clothesInCart.Quantity >= clothesQuantity)
            //    return false;
            //}
            if (clothesInCart != null)
            {
                if (clothesInCart.Quantity < clothesQuantity)
                    return true;
            }
            return false;
        }

        //
        // GET: /Store/AddToCart/5
       [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult AddToCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);            
            string cartId = cart.GetCartId(this.HttpContext);
            // Retrieve the cloth from the database
            var addedCloth = storeDB.Clothes
                .Single(cloth => cloth.ClothesId == id);
            int data;
            //if (addedCloth.Quantity == 0)
           if (!CanAdd(id,cartId))
            {
                data = -1;
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            // Add it to the shopping cart
            //var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedCloth);            
            data=cart.GetCount();
            //RedirectToAction("Index");
           
           return Json(data, JsonRequestBehavior.AllowGet);
           // return Json(data);
        }
         //var ControllerContext.RouteData.GetRequiredString("action")
       [AcceptVerbs(HttpVerbs.Get)]
       public JsonResult AddToCart0(int id)
       {
           var cart = ShoppingCart.GetCart(this.HttpContext);
           string cartId = cart.GetCartId(this.HttpContext);
           // Retrieve the cloth from the database
           var addedCloth = storeDB.Clothes
               .Single(cloth => cloth.ClothesId == id);

           int data;
           if (!CanAdd(id, cartId))
           {
               data = -1;
               return Json(data, JsonRequestBehavior.AllowGet);
           }
           // Add it to the shopping cart
          

           //var cart = ShoppingCart.GetCart(this.HttpContext);

           cart.AddToCart(addedCloth);
           //data = cart.GetCount();
           data = 1;

           return Json(data, JsonRequestBehavior.AllowGet);
           //return RedirectToAction("Index");
       }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the positionName to display confirmation
            string positionName = storeDB.ShoppingCarts
                .Single(item => item.RecordId == id).Cloth.ClothesName;

            // Remove from cart
           // int itemCount = cart.RemoveFromCart(id);
            cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(positionName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                //ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

ASP.NET MVC/UsedClothes/UsedClothes/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UsedClothes.Models;
using UsedClothes.ViewModels;

namespace UsedClothes.Controllers
{
    public class StoreController : Controller
    {
        UCEntities storeDB = new UCEntities();

        //
        // GET: /Store/

        //public ActionResult Index()
        //{
        //    var genres = storeDB.Genres.ToList();

        //    return View(genres);
        //}

        //
        // GET: /Store/Browse?genre=Disco

        //public ActionResult Browse(string genre)
        //{
        //    // Retrieve Genre and its Associated Albums from database
        //    var genreModel = storeDB.Genres.Include("Albums")
        //        .Single(g => g.Name == genre);

        //    return View(genreModel);
        //}

        //
        // GET: /Store/Details/5

        // GET: /Store/GetBookPartialView  method
        private void IncrementDisplayCount(int id)
        {
            storeDB.Clothes.Where(x => x.ClothesId == id).FirstOrDefault().DisplayCount += 1;
            storeDB.SaveChanges();
        }

        public PartialViewResult GetDetailsPartialView(int id/*, string param2*/)
        {
            //id=-1;
            try
            {                
                var cloth = storeDB.GetClothesDetails(id).SingleOrDefault();
                var pictures = storeDB.GetPicturesForClothes(id).ToList();

                if (Request.IsAjaxRequest())
                {
                    var item = new ClothesDetailsWithPicturesViewModel()
                    {
                        ClothesDetails = cloth,
                        PicturesForClothes = pictures
                    };
                    IncrementDisplayCount(id);
                    return PartialView("_Details", item);
                }
                else
                {
                    return null;
                }               
            }
            catch(Exception ex)
            {
                  TempData["Message"] = string.Format("Can't display details");
                  return null;
            }
        }

        public ActionResult Details(int id)
        {
            var cloth = storeDB.GetClothesDetails(id).SingleOrDefault();
            var pictures = storeDB.GetPicturesForClothes(id).ToList();

            var item = new ClothesDetailsWithPicturesViewModel()
                   {
                        ClothesDetails=cloth,
                        PicturesForClothes=pictures
                   };
            IncrementDisplayCount(id);
            return View(item);
        }

        //
        // GET: /Store/GenreMenu

        //[ChildActionOnly]
        //public ActionResult GenreMenu()
        //{
        //    var genres = storeDB.Genres.ToList();

        //    return PartialView(genres);
        //}


    }
}

ASP.NET MVC/UsedClothes/UsedClothes/Views/Store/Details.cshtml
@model UsedClothes.ViewModels.ClothesDetailsWithPicturesViewModel
@using UsedClothes.Helpers
@using ClientDependency.Core.Mvc  

@{
    ViewBag.Title = Model.ClothesDetails.ClothesName;
    Html.RequiresJs("jquery-1.8.3.js", "Scripts", 1);
    Html.RequiresCss("Store.css", "Content", 2);
      

}



<script type="text/javascript"> 
$(document).ready(function () {
    $('.addToCartLink').click(function () {
        var id=$(this).attr('id');
        $.ajax({
            url: '@Url.Action("AddToCart","ShoppingCart")'+'/'+id
        }).done(function(data){
            $('#cart-status').text('Cart('+data+')');
        });
    });
    $('.thumbs a').mouseenter(function (e) {
        var i, to;
        if (e.target.tagName === 'IMG')
            e.target = e.target.parentNode;
        $('.thumbs a').removeClass('selected');
        $(e.target).addClass('selected');
        i = $('.thumbs a').index(e.target);
        to = i * 410 * -1;
        return $('#photo-slide').stop().animate({
            "left": to
        }, 'fast');
    });
});

function addToCart(id) {
    $.ajax({
        url: '@Url.Action("AddToCart0","ShoppingCart")' + '/' + id
    }).done(function (data) {
        if(data==-1)
            $('#msg').text("Can't add this item to your cart");
        else
            window.location.href='@Url.Action("Index","ShoppingCart")';
    });
}

//function success(data) {
//    var json = $.parseJSON(data.responseText);
//     $('#cart-status').text('Cart('+json+')');
//}

</script>

<div id="content">
<div class="columns listing">	
	

    <div class="top">
		<a onclick="javascript:history.go(-1)" id="back-to" href="javascript:void(0)">Back to search results</a>		<h3 class="title">Brand New Volcom Scoop Neck 1/2 sleeve tee!</h3>				
	</div>	
	<div class="left">		
		<div class="price-block">
			<h4>@Model.ClothesDetails.Price</h4>		
		</div>
		<div class="action-block">
			@*<a id="atc" href="@Url.Action("AddToCart0", "ShoppingCart", new { id = Model.ClothesDetails.ClothesId })">      *@
            <a id="atc" href="javascript:addToCart(@Model.ClothesDetails.ClothesId)">
                <em>Add To Cart</em>
            </a>
        </div>		
		<div class="info-block">        
			<p><strong>Item #:</strong> @Model.ClothesDetails.ClothesId</p>			
			<p><strong>Views:</strong> @Model.ClothesDetails.DisplayCount</p>
		</div>
		<div class="info-block">
			<p><strong>Condition:</strong>  @Html.ConditionData(Model.ClothesDetails.Condition,Model.ClothesDetails.IsVintage)</p>
            <p><strong>Size:</strong> @Model.ClothesDetails.SizeName</p>
	        <p><strong>Brand:</strong> @Model.ClothesDetails.BrandName</p>
			<p><strong>Material(s):</strong> @Model.ClothesDetails.MaterialName</p>
			<p><strong>Color/Pattern:</strong> @Model.ClothesDetails.ColorName/@Model.ClothesDetails.PatternName</p>
            <p><strong>Quantity:</strong> @Model.ClothesDetails.Quantity</p>
		</div>
		<div class="info-block">
		<p style="text-transform:none; font-size:14px; font-weight:100;">
		    @Model.ClothesDetails.Description	
        </p>	
		</div>
        <br>
                
                
	</div>
	<div class="main">
	 	<div class="listing-photos">
	<div class="thumbs">			
         @{byte counter=0;}
                    @foreach (var item in Model.PicturesForClothes)
                    {                   
                        if (counter == 0)
                        {  
                             @:<a href="javascript:void(0)" class="selected" > @Html.ImageData(item.PictureId, null) </a>                      
                        }
                        else
                        {
                            @:<a href="javascript:void(0)" class=""> @Html.ImageData(item.PictureId, null)</a>  
                        }
                        counter++;                  
                    }                    
    </div>
	<div id="listing-photo">
		<div id="photo-slide" style="left: 0px;">
		      @foreach (var item in  Model.PicturesForClothes)
                  {             
                    @Html.ImageData(item.PictureId, null)
                  }       
        </div>
	</div>	
</div>


<script type="text/javascript">

    jQuery('.thumbs a').each(function () {
        jQuery(this).mouseover(function () {

            jQuery('.thumbs a').removeClass('selected');
            jQuery(this).addClass('selected');

            var to = parseInt(jQuery(this).attr('rel')) * 410 * -1;
            jQuery('#photo-slide').animate({ "left": to }, 'fast');
        });
    });

</script>	</div>	
	<div class="right"><br>
		<div class="sellerBio">
            <div id="pimg">
	            <img alt="avatar">
            </div>
            <a href="adresSprzedającego">
                <h3>@Model.ClothesDetails.UserName</h3>
            </a>
            @*<span class="location">Portland, OR</span>
            <div class="stats">
                <p></p><h2>100%</h2> from <a href="/users/profile/62101108/feedback">10 reviews</a><p></p></div>
                <div class="desc"><h3>About redtruck</h3>        I'm someone with a lot of cloths and I'm very excited to be up-cycling them on to new owners.  Feel free to ask questions about any of my listings.  Happy shopping.     
            </div>*@
            <div class="actions">
                <a onclick="window.location='/redtruck';" class="listings button-med grey" href="javascript:void(0)">Inne pozycj sprzedającego</a><br>	
            </div>
        </div>	
     </div>
	 <br>    
   </div>
</div>

ASP.NET MVC/UsedClothes/UsedClothes/Views/Store/_Details.cshtml
@model UsedClothes.ViewModels.ClothesDetailsWithPicturesViewModel
@using UsedClothes.Helpers

<script type="text/javascript">
    $(document).ready(function () {
        $('.thumbs a').mouseenter(function (e) {
            var i, to;
            if (e.target.tagName === 'IMG')
                e.target = e.target.parentNode;
            $('.thumbs a').removeClass('selected');
            $(e.target).addClass('selected');
            i = $('.thumbs a').index(e.target);
            to = i * 300 * -1;
            return $('#photo-slide').stop().animate({
                "left": to
            }, 'fast');
        });
         $('#addToCart').click(function (e) {       
                        
            id = $(this).attr('itemId');
          
            $.ajax({
                url: 'ShoppingCart/AddToCart/' + id,
            }).done(function(data){
             
                    $('.action-block .added-to-cart').css({
                        display: 'block'
                    });
                    if (data!=-1){
                        $('.action-block .added-to-cart').text("The item has been added to your cart");
                        $('#cart-status').text('Cart('+data+')');
                    }
                    else{
                        $('.action-block .added-to-cart').text("Can't add this item to your cart");
                    }
                //});

                //
               // if (data==-1)
                //$('#cart-status').text('Cart('+data+')');

                

                //
            });
        });
   });
    //    function ModalClose() {
    //        jQuery('#info-window').fadeOut().remove();
    //        jQuery('.m-screen').remove();
    //    }
 </script>
    

    <a class="m-close" href="javascript:ModalClose();">
        <span>close</span>
    </a>
    @*<div id="quick-view" style="width: 785px; height: 565px;">*@
    <div id="quick-view" >
        <div class="quick-view">
        
            <div class="item-photos"> 
                <div class="thumbs">          
                    @{byte counter=0;}
                    @foreach (var item in Model.PicturesForClothes)
                    {                   
                        if (counter == 0)
                        {  
                             @:<a href="javascript:void(0)" class="selected" > @Html.ImageData(item.PictureId, null) </a>                      
                        }
                        else
                        {
                            @:<a href="javascript:void(0)" class=""> @Html.ImageData(item.PictureId, null)</a>  
                        }
                        counter++;                  
                    }                    
                 </div>
              <div id="listing-photo">	  
              <div id="photo-slide" style="left: 0px;">
              @*@Html.Action("Details", "Store", new { id = @Model.ClothesDetails.ClothesId })*@
                <a href="@Url.Action("Details", "Store", new { id = Model.ClothesDetails.ClothesId, @class="button-med red add-to-cart" })">       
                  @foreach (var item in  Model.PicturesForClothes)
                  {             
                    @Html.ImageData(item.PictureId, null)
                  }                  
                 </a>
              </div>
           </div>
        </div>
        <div class="item-detail">  
            <p class="views">  Views: <strong>@Model.ClothesDetails.DisplayCount</strong>  </p>  
            <p class="title">        
               @Html.ActionLink(@Model.ClothesDetails.ClothesName, "Details", "Store", new { id = @Model.ClothesDetails.ClothesId }, null)
            </p>
            <p class="price"> @Model.ClothesDetails.Price</p>       
       
            <div class="action-block">      
                <a  id="addToCart" itemId="@Model.ClothesDetails.ClothesId" class="button-med red add-to-cart" href="javascript:void(0)">Add To Cart</a>
                @*<a id="fav-1289216153" class="button-med grey favorite" href="javascript:void(0)">Add To Favorites</a>*@
                <a class="added-to-cart" href="@Url.Action("Index", "ShoppingCart")"></a>    
              
             </div>    
             <p class="details">  
                <strong>Condition:</strong>
                    @Html.ConditionData(Model.ClothesDetails.Condition,Model.ClothesDetails.IsVintage)
                    <br>    
                <strong>Size:</strong>@Model.ClothesDetails.SizeName <br>
                <strong>Brand:</strong>@Model.ClothesDetails.BrandName <br>    
                <strong>Material:</strong> @Model.ClothesDetails.MaterialName <br>      
                <strong>Color/Pattern:</strong>@Model.ClothesDetails.ColorName/@Model.ClothesDetails.PatternName<br>    
                <strong>Quantity:</strong>@Model.ClothesDetails.Quantity <br>
              </p>      
              @*<a href="/listings/item/1289216153" class="button-small grey">More Details</a>*@
              @Html.ActionLink("More Details", "Details", "Store", new { id = @Model.ClothesDetails.ClothesId }, new {@class = "button-med red add-to-cart"})
              <div class="seller">    
                <img alt="Avatar" >      
                <p>
                    <strong>Seller:</strong>@Model.ClothesDetails.UserName       
                </p>
                <p>                  
                    @*<strong>Rating:</strong> Not yet rated.   *@
                </p>    
               @* <a class="button-small grey" href="/Tangerina">Tangerina's Store</a>*@
           </div>  
       </div>   
    </div>  
  </div>